# Generated by Django 4.2.3 on 2023-07-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctv_id', models.CharField(max_length=10)),
                ('video', models.FileField(null=True, upload_to='videos_uploaded')),
                ('images', models.ImageField(null=True, upload_to='upload_img')),
                ('adress', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
