# Generated by Django 4.1.1 on 2023-08-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, null=True)),
                ('bland', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('color_plate', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=255)),
            ],
        ),
    ]
